name: Update wiki

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          repository: MemeCrafters/meme-generator-rs
          path: main

      - uses: dtolnay/rust-toolchain@1.85.0
      - uses: swatinem/rust-cache@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt install -y libfontconfig1-dev libfreetype6-dev

      - name: Update memes.md
        run: |
          pip install virtualenv maturin[patchelf]
          cd main/meme_generator_py
          virtualenv .venv
          maturin develop --release
          source .venv/bin/activate
          pip install filetype pillow
          cd ../..
          cargo build --release
          mkdir libraries
          cp target/release/libmeme_generator_contrib.so libraries/
          cp -r main/resources/fonts resources/
          echo -e "[meme]\nload_builtin_memes = false\nload_external_memes = true\n" > config.toml
          export MEME_HOME=.
          python wiki/update_meme_list.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          directory: "wiki"
          repository: ${{ github.repository }}.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "update meme list"
          branch: "master"
